### ISSUE TITLE
[Compilation] left-hand comma expression warnings when compiling

### ISSUE THREAD

**Issue by Cyrillius** [radcheb/Adhan#1]
Here is the warning message:

> avertissement : left-hand operand of comma expression has no effect [-Wunused-value]
>      return (time_components *) (hours, minutes, seconds);

**Comment by Cyrillius** [comment]
prenons un exemple:

```
inline time_components *new_time_components(int *hours, int *minutes, int *seconds){
    return (time_components *) (hours, minutes, seconds);
}
```

Cette méthode retourne un pointeur de struct de type time_components : 

```
typedef struct {
    int hours;
    int minutes;
    int seconds;
} time_components;
```
Je ne pense pas que cela est possible en C ce que je propose est de tout simple faire:

`time_compoents date = {hours,minutes,seconds};`

Il ne faut pas oublier que en C il y a pas de garbage collector donc tous les malloc et new que l''on fait on doit faire vraiment attention de bien les supprimer. De plus il faut éviter cela car cette opération prend quand même beaucoup de temps.

**Comment by radcheb** [comment]
Super merci Cyril pour ces conseil, j em'en suis servi pour réfactorer une bonne partie du code. Est-ce que vous pourriez vérifier si la dernière version de la librairie marche sans problème pour toi ?

**Comment by Cyrillius** [comment]
Désolé je n'ai pas vu passé ce message. Les résultats des test unitaires sont bons?

**Comment by radcheb** [comment]
@Cyrillius : Can we close this?

**Comment by Cyrillius** [comment]
oui on peut fermer cette issue
