### ISSUE TITLE
How to get the angle of Qibla from the library?

### ISSUE THREAD

**Issue by Cyrillius** [radcheb/Adhan#13]
What is the method I need to use to get the direction of the Qibla from the north?

The input of the method should be a location in latitude and longitude.

**Comment by radcheb** [comment]
As far as I know, library adhan does not have any module to get Qibla direction. This is definitely a different subject from getting prayers time.

**Comment by Cyrillius** [comment]
but you have astronomical functions inside the library maybe we can use these functions to implement a method to caclculate the direction of the Qibla I will check what we need

**Comment by Cyrillius** [comment]
Discussed via e-mail the old algorithm to compute the Qibla will be used.
